-- ADD PRIMARY KEY FOR TD_UDB_CIT23P TABLE USING PERSONAL ID (PB030)
ALTER TABLE TD_UDB_CIT23P
ADD CONSTRAINTS PK_TD_UDB_CIT23P PRIMARY KEY (PB030);

-- ADD PRIMARY KEY FOR TD_UDB_CIT23H TABLE USING HOUSEHOLD ID (HB030)
ALTER TABLE TD_UDB_CIT23H
ADD CONSTRAINTS PK_TD_UDB_CIT23H PRIMARY KEY (HB030);

-- ADD PRIMARY KEY FOR TD_UDB_CIT23D TABLE USING HOUSEHOLD ID (DB030)
ALTER TABLE TD_UDB_CIT23D
ADD CONSTRAINTS PK_TD_UDB_CIT23D PRIMARY KEY (DB030);

-- ADD PRIMARY KEY FOR TD_UDB_CIT23R TABLE USING PERSONAL ID (RB030)
ALTER TABLE TD_UDB_CIT23R
ADD CONSTRAINTS PK_TD_UDB_CIT23R PRIMARY KEY (RB030);

COMMIT;