CREATE TABLE C##EUSILC_SVIL.TD_UDB_CIT23_METADATA (
	OWNER	VARCHAR2(128),
	TABLE_NAME	VARCHAR2(128),
	COLUMN_NAME	VARCHAR2(128) NOT NULL,
	DATA_TYPE	VARCHAR2(128),
	DATA_LENGTH	NUMBER,
	DATA_PRECISION	NUMBER,
	DATA_SCALE	NUMBER,
	NULLABLE	VARCHAR2(1),
	TABLE_DESCRIPTION	VARCHAR2(50),
	COLUMN_DESCRIPTION	VARCHAR2(128),
	VALUES_AND_FORMAT	CLOB,
	FLAGS	CLOB,
	OTHERS	VARCHAR2(4000)
);
