MERGE INTO C##EUSILC_SVIL.td_udb_cit23_metadata MET USING SYS.ALL_TAB_COLUMNS COL
ON (MET.COLUMN_NAME = COL.COLUMN_NAME)
WHEN MATCHED THEN
UPDATE
SET
         MET.OWNER = COL.OWNER
        ,MET.TABLE_NAME = COL.TABLE_NAME
        ,MET.DATA_TYPE = COL.DATA_TYPE
        ,MET.DATA_LENGTH = COL.DATA_LENGTH
        ,MET.DATA_PRECISION = COL.DATA_PRECISION
        ,MET.DATA_SCALE = COL.DATA_SCALE
        ,MET.NULLABLE = COL.NULLABLE;
COMMIT;