CREATE OR REPLACE VIEW VA_WEIGHT_AGE_CLASS (AGE_CLASS, FLAG_CLASS, TOT_SAMP, PERC_SAMP, PERC_TURIN, WEIGHT_AGE_CLASS) AS 
WITH TAB_CLASS AS (
SELECT RB030, 
        CASE WHEN 
            2023 - RB080 <= 15 THEN '[0-15]' 
            WHEN 
            2023 - RB080 > 16 AND 2023 - RB080 <= 24 THEN '(15-24]' 
            WHEN 
            2023 - RB080 > 24 AND 2023 - RB080 <= 44 THEN '(24-44]' 
            WHEN 
            2023 - RB080 > 44 AND 2023 - RB080 <= 64 THEN '(44-64]'
            ELSE '64+' 
            END AS AGE_CLASS 
FROM TD_UDB_cIT23R
),
STATS_SAMPLE AS (
SELECT  AGE_CLASS, 
        ROW_NUMBER() OVER(ORDER BY AGE_CLASS) AS FLAG_CLASS, 
        COUNT(*) AS TOT_SAMP, 
        COUNT(*)/4276 AS PERC_SAMP
FROM TAB_CLASS
WHERE SUBSTR(RB030,1,8) IN (
                select DB030 from TD_UDB_cIT23D
                where DB040 = 'ITC' AND DB100 = 1
                )
GROUP BY AGE_CLASS
ORDER BY AGE_CLASS
),
STATS_SAMPLE_TURIN AS(
SELECT S.*,
        CASE 
        WHEN S.FLAG_CLASS = 1 THEN 0.123 
        WHEN S.FLAG_CLASS = 2 THEN 0.080
        WHEN S.FLAG_CLASS = 3 THEN 0.235
        WHEN S.FLAG_CLASS = 4 THEN 0.302
        ELSE 0.260 END AS PERC_TURIN
FROM STATS_SAMPLE S
)
SELECT  
        ST.AGE_CLASS,
        ST.FLAG_CLASS,
        ST.TOT_SAMP,
        ROUND(ST.PERC_SAMP , 3) AS PERC_SAMP,
        ST.PERC_TURIN,
        ROUND(ST.PERC_TURIN/ST.PERC_SAMP , 3) AS WEIGHT_AGE_CLASS
FROM STATS_SAMPLE_TURIN ST;