CREATE OR REPLACE VIEW VA_WEIGHT_SEX (SEX, RB090, TOT_SAMP, PERC_SAMP, PERC_TURIN, WEIGHT_SEX) AS 
WITH SEX AS (
SELECT  CASE WHEN RB090 = 1 THEN 'MALE' ELSE 'FEMALE' END AS SEX,
        RB090,
        COUNT(*) AS TOT_SAMP,
        COUNT(*)/4276 AS PERC_SAMP
FROM TD_UDB_cIT23R
WHERE SUBSTR(RB030,1,8) IN (
                select DB030 from TD_UDB_cIT23D
                where DB040 = 'ITC' AND DB100 = 1
                )
GROUP BY RB090
),
STATS_SAMPLE_TURIN AS (
SELECT  S.*,
        CASE WHEN S.RB090 = 2 THEN 0.52 ELSE 0.48 END AS PERC_TURIN
FROM SEX S
)
SELECT 
    SEX,
    RB090,
    TOT_SAMP,
    ROUND(PERC_SAMP , 3) AS PERC_SAMP,
    ROUND(PERC_TURIN , 3) AS PERC_TURIN,
    ROUND(PERC_TURIN/PERC_SAMP , 3) AS WEIGHT_SEX
FROM STATS_SAMPLE_TURIN;