CREATE OR REPLACE VIEW VA_WEIGHT_MEMBERS (N_COMPONENTS, HB120, TOT_SAMP, PERC_SAMP, PERC_TURIN, WEIGHT_MEMBERS) AS 
WITH MEMBERS AS (
SELECT 
        HB030, 
        CASE WHEN HB120 >= 6 THEN 6 ELSE HB120 END AS HB120 
FROM td_udb_cit23h
),
STATS_SAMPLE AS (
SELECT 
        HB120 AS N_COMPONENTS, 
        HB120,
        COUNT(*) AS TOT_SAMP, 
        COUNT(*)/2248 AS PERC_SAMP 
FROM MEMBERS WHERE HB030 IN (
                select DB030 from TD_UDB_cIT23D
                where DB040 = 'ITC' AND DB100 = 1
                )
GROUP BY HB120
ORDER BY HB120
),
STATS_SAMPLE_TURIN AS(
SELECT S.*,
        CASE 
        WHEN S.HB120 = 1 THEN 0.491 
        WHEN S.HB120 = 2 THEN 0.261
        WHEN S.HB120 = 3 THEN 0.133
        WHEN S.HB120 = 4 THEN 0.087
        WHEN S.HB120 = 5 THEN 0.021
        ELSE 0.008 END AS PERC_TURIN
FROM STATS_SAMPLE S
)
SELECT  
        ST.N_COMPONENTS,
        ST.HB120,
        ST.TOT_SAMP,
        ROUND(ST.PERC_SAMP , 3) AS PERC_SAMP,
        ST.PERC_TURIN,
        ROUND(ST.PERC_TURIN/ST.PERC_SAMP , 3) AS WEIGHT_MEMBERS
FROM STATS_SAMPLE_TURIN ST;